### ISSUE TITLE
Update to fix https://github.com/pi-hole/docker-pi-hole/issues/794

### ISSUE THREAD

**Issue by GuillaumeSmaha** [jacklul/pihole-updatelists#101]
Hi,
Thanks a lot for your work.
Is it possible to trigger a push of a new docker image ? There is this issue https://github.com/pi-hole/docker-pi-hole/issues/794 which was fixed recently and your latest build have the issue.

**Comment by jacklul** [comment]
Last update to the latest image was 2 months ago, my image is up to date.
If this fix is merged to their dev image then I suggest writing custom Dockerfile to pull it (my dev image still pulls their latest).

https://hub.docker.com/layers/pihole/pihole/pihole/latest/images/sha256-e2dff636c08214c8ca575e924ffbcd2e8e3ce10552c1582390a23e63d486d573
https://hub.docker.com/layers/pihole/jacklul/pihole/latest/images/sha256-a2a262cc68c62f149c1fe6d1c027c47fb6633bad509d5f88cf24085ff5e24da7

**Comment by GuillaumeSmaha** [comment]
Sorry I totally misreading the year between 2021 & 2022 :facepalm:
I still have an issue using your version or any version based on pihole:latest.
My current issue is pihole-FTL which starts and directly dies without information (infinite loop of restart) but it was working when I upgraded at first.
I succeeded to build your Dockerfile using pihole:v5.8 and it solves the issue for now.

I am closing the issue and sorry again for my misreading of the year :facepalm:
